### ISSUE TITLE
Issue with reading directly from DataFrame during differential testing

### ISSUE THREAD

**Issue by arnscott** [InfectionMedicineProteomics/DPKS#25]
* dpks version:
* Python version:
* Operating System:

### Description

There is an issue with indexing when the input is a dataframe and now a text file. 

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ErikHartman** [comment]
I guess this is fixed? Close?

**Comment by arnscott** [comment]
Yes, this was complete. I will close it
